import { app, BrowserWindow, ipcMain } from 'electron';
import { readFileSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import * as agents from './main/agents';
import * as backend from './main/backend';
import * as providerRegistry from './main/providers';
import * as environments from './main/environments';
import * as runner from './main/runner';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1120,
    minHeight: 520,
    minWidth: 720,
    backgroundColor: '#FFFDF7',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// Harness bridge: the renderer starts turns here; events stream back tagged
// with the turnId so concurrent turns can't interleave. Providers (Claude
// Code / Codex) run inside the active environment's Docker container.
ipcMain.handle('harness:status', () => backend.status());
ipcMain.handle('provider:list', () => backend.providerInfos());
ipcMain.handle('agent:list', () => agents.list());
ipcMain.handle('agent:create', (_event, cfg) => agents.create(cfg));
ipcMain.handle('agent:update', (_event, args: { id: string; cfg: never }) =>
  agents.update(args.id, args.cfg),
);
ipcMain.handle('agent:delete', (_event, id: string) => agents.remove(id));
ipcMain.handle('agent:select', (_event, id: string) => {
  agents.select(id);
  return backend.status();
});
ipcMain.handle('provider:auth-start', async (_event, id: string) => {
  const url = await backend.provider(id).auth.start();
  return { url };
});
ipcMain.handle('provider:auth-logout', (_event, id: string) => {
  backend.provider(id).auth.logout();
});

ipcMain.handle('env:list', () => environments.list());
ipcMain.handle('env:create', (_event, cfg) => environments.create(cfg));
ipcMain.handle('env:update', (_event, args: { id: string; cfg: never }) =>
  environments.update(args.id, args.cfg),
);
ipcMain.handle('env:delete', (_event, id: string) => {
  runner.detach(id);
  return environments.remove(id);
});
ipcMain.handle('env:start', (_event, id: string) => environments.start(id));
ipcMain.handle('env:stop', (_event, id: string) => {
  runner.detach(id);
  return environments.stop(id);
});
ipcMain.handle('env:restart', (_event, id: string) => {
  runner.detach(id);
  return environments.restart(id);
});
ipcMain.handle('env:rebuild', (_event, id: string) => {
  runner.detach(id);
  return environments.rebuild(id);
});
ipcMain.handle('env:secret-set', (_event, args: { id: string; key: string; value: string }) =>
  environments.secretSet(args.id, args.key, args.value),
);
ipcMain.handle('env:secret-delete', (_event, args: { id: string; key: string }) =>
  environments.secretDelete(args.id, args.key),
);
ipcMain.handle('env:select', (_event, id: string) => {
  environments.select(id);
  return backend.status();
});

// Logins complete inside the app's sign-in window; push credentials into
// running environments the moment they land.
providerRegistry.setOnLogin(() => void environments.injectCredentialsIntoRunning());

// Long-lived per-agent conversation transcripts.
const convoPath = () => path.join(app.getPath('userData'), 'puck-convos.json');
function readConvos(): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(convoPath(), 'utf8')) as Record<string, unknown>;
  } catch {
    return {};
  }
}
ipcMain.handle('convo:load', () => readConvos());
ipcMain.handle('convo:save', (_event, args: { agentId: string; data: unknown }) => {
  const all = readConvos();
  all[args.agentId] = args.data;
  writeFileSync(convoPath(), JSON.stringify(all));
});

ipcMain.handle(
  'harness:start-turn',
  async (event, args: { turnId: string; agentId: string; prompt: string }) => {
    for await (const harnessEvent of backend.runTurn(args.turnId, args.agentId, args.prompt)) {
      if (event.sender.isDestroyed()) return;
      event.sender.send('harness:event', { turnId: args.turnId, event: harnessEvent });
    }
  },
);
ipcMain.handle('harness:interrupt', (_event, turnId: string) => backend.interrupt(turnId));
ipcMain.handle(
  'harness:answer-ask',
  (_event, args: { turnId: string; askId: string; answers: Record<string, string> | null }) =>
    backend.answerAsk(args.turnId, args.askId, args.answers),
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
