import { app, BrowserWindow, ipcMain, session, shell } from 'electron';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as agents from './main/agents';
import * as backend from './main/backend';
import * as providerRegistry from './main/providers';
import * as environments from './main/environments';
import * as runner from './main/runner';
import { agentConfigFrom, envConfigFrom, requireId } from './main/ipcguard';
import { readJson, writeJsonAtomic } from './main/jsonstore';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1120,
    minHeight: 520,
    minWidth: 720,
    backgroundColor: '#FFFDF7',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      sandbox: true,
      nodeIntegration: false,
      // Streaming render batches on requestAnimationFrame; an occluded
      // window must keep painting background conversations truthfully.
      backgroundThrottling: false,
    },
  });

  // The window must never leave the app: chat renders remote-authored
  // markdown, and a navigated page would inherit the preload's IPC bridge.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:/i.test(url)) void shell.openExternal(url);
    return { action: 'deny' };
  });
  mainWindow.webContents.on('will-navigate', (event, url) => {
    if (url !== MAIN_WINDOW_WEBPACK_ENTRY) {
      event.preventDefault();
      if (/^https?:/i.test(url)) void shell.openExternal(url);
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// Harness bridge: the renderer starts turns here; events stream back tagged
// with the turnId so concurrent turns can't interleave. Providers (Claude
// Code / Codex) run inside the active environment's Docker container.
ipcMain.handle('harness:status', () => backend.status());
ipcMain.handle('provider:list', () => backend.providerInfos());
ipcMain.handle('shell:open-external', (_event, url: unknown) => {
  if (typeof url === 'string' && /^https?:\/\//i.test(url)) void shell.openExternal(url);
});
ipcMain.handle('agent:list', () => agents.list());
ipcMain.handle('agent:create', (_event, cfg: unknown) => agents.create(agentConfigFrom(cfg)));
ipcMain.handle('agent:update', (_event, args: { id: unknown; cfg: unknown }) =>
  agents.update(requireId(args.id, 'agent'), agentConfigFrom(args.cfg)),
);
ipcMain.handle('agent:delete', (_event, id: unknown) => agents.remove(requireId(id, 'agent')));
ipcMain.handle('agent:select', (_event, id: unknown) => {
  agents.select(requireId(id, 'agent'));
  return backend.status();
});
ipcMain.handle('provider:auth-start', async (_event, id: unknown) => {
  const url = await backend.provider(requireId(id, 'provider')).auth.start();
  return { url };
});
ipcMain.handle('provider:auth-logout', (_event, id: unknown) => {
  backend.provider(requireId(id, 'provider')).auth.logout();
});

ipcMain.handle('env:list', () => environments.list());
ipcMain.handle('env:create', (_event, cfg: unknown) => environments.create(envConfigFrom(cfg)));
ipcMain.handle('env:update', (_event, args: { id: unknown; cfg: unknown }) =>
  environments.update(requireId(args.id, 'environment'), envConfigFrom(args.cfg)),
);
ipcMain.handle('env:delete', (_event, id: unknown) => {
  const envId = requireId(id, 'environment');
  runner.detach(envId);
  return environments.remove(envId);
});
ipcMain.handle('env:start', (_event, id: unknown) =>
  environments.start(requireId(id, 'environment')),
);
ipcMain.handle('env:stop', (_event, id: unknown) => {
  const envId = requireId(id, 'environment');
  runner.detach(envId);
  return environments.stop(envId);
});
ipcMain.handle('env:restart', (_event, id: unknown) => {
  const envId = requireId(id, 'environment');
  runner.detach(envId);
  return environments.restart(envId);
});
ipcMain.handle('env:rebuild', (_event, id: unknown) => {
  const envId = requireId(id, 'environment');
  runner.detach(envId);
  return environments.rebuild(envId);
});
ipcMain.handle('env:secret-set', (_event, args: { id: unknown; key: unknown; value: unknown }) => {
  const envId = requireId(args.id, 'environment');
  runner.detach(envId); // next turn's runner picks up the new secrets file
  return environments.secretSet(
    envId,
    typeof args.key === 'string' ? args.key : '',
    typeof args.value === 'string' ? args.value : '',
  );
});
ipcMain.handle('env:secret-delete', (_event, args: { id: unknown; key: unknown }) => {
  const envId = requireId(args.id, 'environment');
  runner.detach(envId);
  return environments.secretDelete(envId, typeof args.key === 'string' ? args.key : '');
});
ipcMain.handle('env:select', (_event, id: unknown) => {
  environments.select(requireId(id, 'environment'));
  return backend.status();
});

// Logins complete inside the app's sign-in window; push credentials into
// running environments the moment they land.
providerRegistry.setOnLogin(() => void environments.injectCredentialsIntoRunning());

// Long-lived per-agent conversation transcripts: one file per agent, written
// atomically, so a crash can never truncate more than one agent's history —
// and never a partially-written file.
const convoDir = () => path.join(app.getPath('userData'), 'puck-convos');
const legacyConvoPath = () => path.join(app.getPath('userData'), 'puck-convos.json');

function readConvos(): Record<string, unknown> {
  const all: Record<string, unknown> = {};
  // One-time migration from the old single-blob store.
  const legacy = readJson<Record<string, unknown>>(legacyConvoPath());
  if (legacy) Object.assign(all, legacy);
  try {
    for (const file of fs.readdirSync(convoDir())) {
      if (!file.endsWith('.json')) continue;
      const data = readJson<unknown>(path.join(convoDir(), file));
      if (data) all[file.slice(0, -5)] = data;
    }
  } catch {
    // directory doesn't exist yet
  }
  return all;
}

ipcMain.handle('convo:load', () => readConvos());
ipcMain.handle('convo:save', (_event, args: { agentId: unknown; data: unknown }) => {
  const agentId = requireId(args.agentId, 'agent');
  return writeJsonAtomic(path.join(convoDir(), `${agentId}.json`), args.data);
});

ipcMain.handle(
  'harness:start-turn',
  async (event, args: { turnId: string; agentId: string; prompt: string }) => {
    for await (const harnessEvent of backend.runTurn(args.turnId, args.agentId, args.prompt)) {
      if (event.sender.isDestroyed()) return;
      event.sender.send('harness:event', { turnId: args.turnId, event: harnessEvent });
    }
  },
);
ipcMain.handle('harness:interrupt', (_event, turnId: string) => backend.interrupt(turnId));
ipcMain.handle(
  'harness:answer-ask',
  (_event, args: { turnId: string; askId: string; answers: Record<string, string> | null }) =>
    backend.answerAsk(args.turnId, args.askId, args.answers),
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  // Packaged builds get a strict CSP; dev needs webpack's eval sourcemaps,
  // covered by the WebpackPlugin devContentSecurityPolicy instead.
  if (app.isPackaged) {
    session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          'Content-Security-Policy': [
            "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:",
          ],
        },
      });
    });
  }
  createWindow();
});

// Kill runner docker-exec children on quit — no orphaned processes.
app.on('before-quit', () => runner.detachAll());

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
